name: Paths Filter Example

on: [push, workflow_dispatch]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          workflows:
            - '.github/workflows/**'
    # run only if 'workflows' files were changed
    - name: workflow tests
      if: steps.filter.outputs.workflows == 'true'
      run: echo "Workflow file"

    # run only if not 'workflows' files were changed
    - name: not workflow tests
      if: steps.filter.outputs.workflows != 'true'
      run: echo "NOT workflow file"
      
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/workflow-2.yml

  next-job:
    runs-on: ubuntu-latest
    # Wait from the paths-filter to be completed before starting next-job
    needs: paths-filter
    if: needs.paths-filter.outputs.output1 == 'true'
    steps:
      - run: |
         echo "test"
